-- Seed workshops for Dali & Sichuan (run after migration)

insert into workshops (slug, title, description, long_description, region, location, duration_hours, max_participants, price_cents, image_url, gallery_urls, highlights, includes, host_name, host_bio, language, featured) values
(
  'bai-ethnic-tie-dye',
  'Bai Ethnic Tie-Dye Workshop',
  'Learn centuries-old indigo tie-dye techniques from Bai artisans in a courtyard studio near Erhai Lake.',
  'Spend a half-day with master artisan Yang Mei in her family courtyard workshop. You will learn the full process: folding, binding, dipping in natural indigo vats, and unwrapping your creation. Every participant leaves with a hand-dyed scarf or tote bag. No experience needed — instruction is fully in English with visual demonstrations.',
  'dali',
  'Xizhou Ancient Town, Dali',
  4,
  10,
  6800,
  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80',
  array['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80','https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80'],
  array['Natural indigo dyes','Take home your creation','English-speaking guide','Tea & local snacks'],
  array['All materials','Apron & gloves','Scarf or tote to dye','Pickup from Dali Old Town'],
  'Yang Mei',
  'Third-generation Bai tie-dye artisan from Xizhou. Featured in National Geographic Traveler.',
  'English',
  true
),
(
  'erhai-cycling-pottery',
  'Erhai Lakeside Cycling & Pottery',
  'Morning bike ride along Erhai Lake followed by hand-building pottery in a lakeside studio.',
  'Start with a guided e-bike ride along the western shore of Erhai Lake, stopping at Bai villages and photo points. Return to our lakeside studio for a relaxed pottery session — pinch pots, bowls, or decorative pieces. Pieces are fired and shipped internationally within 3 weeks.',
  'dali',
  'Caohai Wetland, Dali',
  6,
  8,
  9500,
  'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80',
  array['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80','https://images.unsplash.com/photo-1610701596007-d2b0fd7d7613?w=800&q=80'],
  array['E-bike included','Lakeside scenery','Ship pottery worldwide','Small group (max 8)'],
  array['E-bike rental','Pottery materials & firing','Lunch','International shipping'],
  'Li Wei',
  'Ceramic artist and cycling guide. Studied at Jingdezhen and lived in Dali for 12 years.',
  'English',
  true
),
(
  'sichuan-hotpot-cooking',
  'Authentic Sichuan Hotpot Cooking Class',
  'Master the art of Sichuan hotpot — from broth to dipping sauces — in a Chengdu home kitchen.',
  'Join Chef Zhang in her Chengdu apartment for an immersive cooking experience. Learn to prepare two broths (spicy mala and mild mushroom), make signature dipping sauces, and understand the philosophy behind Sichuan flavor layering. End with a full hotpot feast with local beer.',
  'sichuan',
  'Jinjiang District, Chengdu',
  3,
  12,
  7500,
  'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=1200&q=80',
  array['https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&q=80'],
  array['Home kitchen experience','Recipe cards to take home','Market visit optional','Vegetarian options'],
  array['All ingredients','Recipes (EN/CN)','Full hotpot meal','Local beer or tea'],
  'Chef Zhang Lin',
  'Former restaurant chef with 20 years of Sichuan cuisine expertise. Featured on Chengdu food tours.',
  'English',
  true
),
(
  'shuimo-painting-pandas',
  'Chinese Ink Painting & Panda Sanctuary Visit',
  'Morning ink painting lesson followed by an afternoon at the Chengdu Research Base of Giant Panda Breeding.',
  'Begin with a 2-hour shuimo (ink wash) painting workshop focusing on bamboo and pandas — techniques passed down through classical Chinese art. After lunch, we visit the panda base with an expert guide who explains conservation efforts. Painting supplies included; take your artwork home.',
  'sichuan',
  'Wuhou District, Chengdu',
  8,
  10,
  12800,
  'https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=1200&q=80',
  array['https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=800&q=80'],
  array['Ink painting masterclass','Panda base entry included','Small group guide','Art supplies included'],
  array['Painting materials','Panda base ticket','Transport to base','Lunch'],
  'Professor Wang',
  'Retired Sichuan Fine Arts Academy instructor. Published artist specializing in ink wash landscapes.',
  'English',
  false
),
(
  'tea-ceremony-mount-emei',
  'Mount Emei Tea Ceremony & Forest Walk',
  'Experience a traditional Sichuan tea ceremony amid ancient forests at the foot of Mount Emei.',
  'Travel to a tea plantation at the base of Mount Emei for a guided forest walk and full gongfu tea ceremony. Learn about Emei snow bud tea, proper brewing technique, and the meditative aspects of Chinese tea culture. Includes tasting of three rare local teas.',
  'sichuan',
  'Emeishan City, Sichuan',
  5,
  8,
  8900,
  'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=1200&q=80',
  array['https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&q=80'],
  array['Mount Emei setting','Gongfu ceremony','Rare tea tastings','Forest meditation walk'],
  array['Tea tastings','Ceremony instruction','Forest guide','Round-trip transport from Emei town'],
  'Chen Yu',
  'Certified tea sommelier and Mount Emei native. 15 years guiding cultural experiences.',
  'English',
  false
),
(
  'nuodeng-salt-well-hike',
  'Nuodeng Ancient Salt Village Hike',
  'Trek through a 1300-year-old salt-trading village in the mountains between Dali and Lijiang.',
  'Discover Nuodeng, one of Yunnan''s best-preserved ancient villages, perched on a hillside with thousand-year-old salt wells still in use. Guided hike through terraced paths, visit a salt workshop, and enjoy a traditional Bai lunch with the village elder.',
  'dali',
  'Nuodeng Village, Yunlong County',
  7,
  10,
  11000,
  'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=1200&q=80',
  array['https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&q=80'],
  array['Off-the-beaten-path','Living salt wells','Bai village lunch','Expert local guide'],
  array['Guide fees','Traditional lunch','Transport from Dali','Hiking poles'],
  'Zhao Bin',
  'Local historian and hiking guide born in Nuodeng. Fluent in English and Bai language.',
  'English',
  false
);

-- Sample sessions (next 60 days)
insert into workshop_sessions (workshop_id, starts_at, ends_at, spots_available)
select w.id,
  (current_date + (n || 7) * interval '1 day' + time '09:00') at time zone 'Asia/Shanghai',
  (current_date + (n || 7) * interval '1 day' + time '09:00' + (w.duration_hours || ' hours')::interval) at time zone 'Asia/Shanghai',
  w.max_participants - (n % 3)
from workshops w
cross join generate_series(1, 4) as n;
